bangazonworkforcemgt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrapp.urls'))
]

hrapp/urls.py
from django.urls import path
from django.conf.urls import include
from hrapp import views
from django.contrib.auth import views as auth_views
from .views import *


app_name = 'hrapp'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view()),
    path('logout/', logout_user, name='logout'),
    path('employees/', employee_list, name='employee_list'),
    path('employee/form/', employee_form, name='employee_form'),
    path('employees/<int:employee_id>/', employee_details, name='employee'),
    path('training_programs/', training_programs_list, name='training_programs'),
    path('training_program_form/', training_program_form, name='program_form'),
    path('computers/', computer_list, name='computer_list'),
    path('computer/<int:computer_id>/', computer_details, name='computer_details'),
    path('computer/form', computer_form, name='computer_form'),
    path('departments/', department_list, name='department_list'),
]

hrapp/models/computer.py
from django.db import models

class Computer(models.Model):
    '''
    description: This class creates a computer and its properties
    author: Joe Shep/Krystal Gates
    properties:
      make: The make will contain the name of the brand of the computer.
      purchase_date: This property contains the purchase date in string form.
      decomission_date: This property contains the dicomission date in string form.
      employees: This property contains the many to many relationship with the computer/employee model
    '''

    manufacturer = models.CharField(max_length=25, default=None)
    model = models.CharField(max_length=25, default=None)
    purchase_date = models.DateField()
    decommission_date = models.DateField(null=True, blank=True, default=None)
    employees = models.ManyToManyField("Employee", through='EmployeeComputer')

    class Meta:
        verbose_name = ("Computer")
        verbose_name_plural = ("Computers")

    def get_absolute_url(self):
        return reverse("Computer_detail", kwargs={"pk": self.pk})

hrapp/models/department.py
from django.db import models

class Department(models.Model):
    '''
    specific department information
    '''

    department = models.CharField(max_length=100)
    budget = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = ("Department")
        verbose_name_plural = ("Departments")

    def __str__(self):
        return f"{self.department} {self.budget}"

    def get_absolute_url(self):
        return reverse("Department", kwargs={"pk": self.pk})

hrapp/models/employee.py
from django.db import models
from .department import Department

class Employee(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    start_date = models.DateField()
    is_supervisor = models.BooleanField()
    department = models.ForeignKey(Department, default=None, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Employee")
        verbose_name_plural = ("Employees")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("Employee_detail", kwargs={"pk": self.pk})

hrapp/models/employee_computer.py
from django.db import models

class EmployeeComputer(models.Model):
    """
    Creates the join table for the many to many relationship between computers and employees
    assigned_date: The date the computer is assigned to employee.
    unassigned_date: The date the computer is unassigned to employee.
    Author: Joe Shep/Krystal Gates
    methods: none
    """

    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    computer = models.ForeignKey("Computer", on_delete=models.CASCADE)
    assigned_date = models.DateField(default=None)
    unassigned_date = models.DateField(null=True, blank=True, default=None)

hrapp/models/training_program.py
from django.db import models
# from .department import Department

class TrainingProgram(models.Model):

    title = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    capacity = models.IntegerField()

    class Meta:
        verbose_name = ("Training_Program")
        verbose_name_plural = ("Training_Programs")

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("Training_program_detail", kwargs={"pk": self.pk})

hrapp/models/training_program_employee.py
from django.db import models

class TrainingProgramEmployee(models.Model):
    

    employee = models.ForeignKey("Employee", on_delete=models.CASCADE)
    training_program = models.ForeignKey("TrainingProgram", on_delete=models.CASCADE)

    
    

hrapp/views/connection_template.py
class Connection:
    db_path = " --Insert File path here-- "

hrapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

hrapp/templates/computers/computer_detail.html
{% extends 'shared/base.html' %}

{% block content %}

    <h1>{{ computer.manufacturer }} {{ computer.model }}</h1>
    <h2>Purchased: {{ computer.purchase_date}}

{% endblock %}

hrapp/templates/computers/computer_form.html
{% extends 'shared/base.html' %}

{% block content %}

    <h1>Inventory Computer</h1>
        <form action="{% url 'hrapp:computer_list' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <label for="manufacturer">Manufacturer: </label>
            <input id="manufacturer" type="text" name="manufacturer" >
        </fieldset>
        <fieldset>
            <label for="model">Model: </label>
            <input id="model" type="text" name="model" >
        </fieldset>
        <fieldset>
            <label for="purchase_date">Purchase Date: </label>
            <input id="purchase_date" type="date" name="purchase_date" >
        </fieldset>
            <label for="employee">Assign to: </label>
            <select id="employee" type="text" name="employee">
                <option value="Null"/>
                {% for employee in all_employees %}
                <option value="{{ employee.id }}">
                    {{ employee.first_name }} {{ employee.last_name }} </option>
                {% endfor %}
            </select>
        </fieldset>
            <input type="submit" value="Create" />
    </form>

{% endblock %}

hrapp/templates/computers/computer_list.html
{% extends 'shared/base.html' %}

{% block content %}

    <h1>Computers</h1>
    {% if request.user.is_authenticated %}
      <a href="{% url 'hrapp:computer_form' %}">Add Computer to Inventory</a>
    {% endif %}
    <ul>
    {% for computer in all_computers %}
        <li>
          <a href="{% url 'hrapp:computer_details' computer.id %}">
          {{ computer.manufacturer }} {{computer.model}}
          </a>
        </li>
    {% endfor %}
    </ul>

{% endblock %}

hrapp/templates/departments/departments_list.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>Departments</h1>

<ol>
{% for department in departments %}
    <li>
        <p>Department: {{department.department}}</p>
        <p>Budget: ${{department.budget}}</p>
        <p>Department Size: {{department.employee}}</p>
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/departments/form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Department</title>
</head>

<body>
    <h1>Add New Department</h1>

    {% if department.id is not None %}
        <form action="{% url 'hrapp:deparment' department.id %}" method="post">
    {% else %}
        <form action="{% url 'hrapp:departments' %}" method="post">
    {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="department">Department: </label>
            <input id="department" type="text" name="department" value="{{ department.department }}">
        </fieldset>
        <fieldset>
            <label for="budget">Budget: </label>
            <input id="budget" type="text" name="budget" value="{{ department.budget }}">
        </fieldset>
        {% if department.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}

    </form>
</body>

</html>

hrapp/templates/employees/details.html
{% extends 'shared/base.html' %}
{% block content %}
<h1>Employee Details</h1>
<section id="employee-detail">
        <p>{{ employee.first_name }} {{ employee.last_name}}</p>
        <p> {{ employee.start_date }}</p>
        <p>{{ employee.department }}</p>
    </section>
{% endblock %}

hrapp/templates/employees/employees_list.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>Employees</h1>
<a href="{% url 'hrapp:employee_form' %}">Add Employee</a>

<ol>
{% for employee in all_employees %}
    <li>
        <a href="{% url 'hrapp:employee' employee.id %}"> {{ employee }} </a>
        <p>{{ employee.department_thing }}</p>
        
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/employees/form.html
{% extends 'shared/base.html' %}
{% block content %}
    <h1>Add employee</h1>

    {% if employee.id is not None %}
        <form action="{% url 'hrapp:employee_list' %}" method="post">
    {% else %}
        <form action="{% url 'hrapp:employee_list' %}" method="post">
    {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="first_name">First Name: </label>
            <input id="first_name" type="text" name="first_name" value="{{ employee.first_name }}">
        </fieldset>
        <fieldset>
            <label for="last_name">Last Name: </label>
            <input id="last_name" type="text" name="last_name" value="{{ employee.last_name }}">
        </fieldset>
        <fieldset>
            <label for="start_date">Start Date: </label>
            <input id="start_date" type="date" name="start_date" value="{{ employee.start_date }}">
        </fieldset>
        <fieldset>
            <label for="department">Department: </label>
            <select id="department" type="text" name="department">
                {% for department in all_departments %}
                <option {% if department.id == employee.department_id %}selected{% endif %} value="{{ department.id }}">
                    {{ department.department }}</option>
                {% endfor %}
            </select>
        </fieldset>

        {% if employee.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}

    </form>
    {% endblock %}

hrapp/templates/home.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>Welcome, {{user}}, to the Bangazon Workforce Management System</h1>
{% endblock content %}

hrapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bangazon Workforce Management</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" />

    {% block css %}
    {% endblock %}

</head>

<body>
<nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'hrapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'hrapp:department_list' %}">Departments</a></li>
            <li class="navList__route"><a href="{% url 'hrapp:employee_list' %}">Employees</a></li>
            <li class="navList__route"><a href="{% url 'hrapp:training_programs' %}">Training Programs</a></li>
            <li class="navList__route"><a href="{% url 'hrapp:computer_list' %}">Computers</a></li>
            {% if request.user.is_authenticated %}
                <li class="navList__route"><a href="{% url 'hrapp:logout' %}">Logout</a></li>
            {% else %}
                <li class="navList__route"><a href="{% url 'hrapp:login' %}">Login</a></li>
            {% endif %}
        </ol>
    </nav>


    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

hrapp/templates/training_programs/training_program_form.html
{% extends 'shared/base.html' %}

{% block content %}

    <h1>Create New Training Program</h1>


    <form action="{% url 'hrapp:training_programs' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Program Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="description">Program Description: </label>
          <!-- <textarea id="description"></textarea> -->
          <input id ="description" type="text" name="description">
      </fieldset>
      <fieldset>
        <label for="start_date">Start Date: </label>
        <input id="start_date" type="date" name="start_date">
    </fieldset>
    <fieldset>
        <label for="end_date">End Date: </label>
        <input id="end_date" type="date" name="end_date">
    </fieldset>
    <fieldset>
        <label for="capacity">Capacity: </label>
        <input id="capacity" type="number" name="capacity">
    </fieldset>

      <input type="submit" value="Add It" />
    </form>

{% endblock %}

hrapp/templates/training_programs/training_programs_list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'styles/program_list.css' %}" type="text/css" media="screen" />
{% endblock %}

{% block content %}
<h1>Training Programs</h1>
<a href="{% url 'hrapp:program_form' %}"><h4>Create New Training Program</h4></a>
<h2>Future Training</h2>
<ol>
{% for program in programs %}
    {% if program.start_date > time.today %}
    <li>
        <p>{{ program.title }}</p>
    </li>
    {% endif %}
{% endfor %}
</ol>
<button id="reveal_past" onclick="showPastPrograms()">Show Past Training</button>
<div id="hidden" class>
<h2>Past Training</h2>
<ol>
    {% for program in programs %}
        {% if program.start_date < time.today %}
        <li>
            <p>{{ program.title }}</p>
        </li>
        {% endif %}
    {% endfor %}
</ol>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'scripts/program_list.js' %}"></script>
{% endblock scripts %}